config/routes.rb
Filesucker::Application.routes.draw do
  resources :folders

  resources :assets
  match "assets/get/:id" => "assets#get", :as => "download" ,via: [:get]

  match "browse/:folder_id" => "home#browse", :as => "browse" , via: [:get]

  match "browse/:folder_id/new_folder" => "folders#new", :as => "new_sub_folder" , via: [:get]
  match "browse/:folder_id/new_file" => "assets#new", :as => "new_sub_file", via:[:get]

  match "browse/:folder_id/rename" => "folders#edit", :as => "rename_folder" , via:[:get]

  # for sharing folders
  match "home/share" => "home#share" , via:[:post]

  devise_for :users
  get "home/index"
  root :to => "home#index"

end

app/models/folder.rb
class Folder < ActiveRecord::Base
  acts_as_tree

  has_many :assets, :dependent => :destroy

  has_many :shared_folders, :dependent => :destroy

  belongs_to :user
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: [:show, :update, :destroy]
  before_filter :authenticate_user!

  def index
    @folders = current_user.folders.all
  end

  def show
  end

  def new
    @folder = current_user.folders.new
    if params[:folder_id]
       @current_folder = current_user.folders.find(params[:folder_id])
       @folder.parent_id = @current_folder.id
    end
  end

  def edit
    @folder = current_user.folders.find(params[:folder_id])
    @current_folder = @folder.parent    #this is just for breadcrumbs
  end

  def create
    @folder = current_user.folders.new(folder_params)
    if @folder.save
      flash[:notice] = "Successfully created folder."
      if @folder.parent #checking if we have a parent folder on this one
        redirect_to browse_path(@folder.parent)  #then we redirect to the parent folder
      else
        redirect_to root_url #if not, redirect back to home page
      end
    else
      render :action => 'new'
    end
  end

  def update
    respond_to do |format|
      if @folder.update(folder_params)
        format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @folder.destroy
    respond_to do |format|
      format.html { redirect_to folders_url }
      format.json { head :no_content }
    end
  end

  private
    def set_folder
      @folder = current_user.folders.find(params[:id])
    end

    def folder_params
      params.require(:folder).permit(:name, :parent_id, :user_id)
    end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_form.html.haml
= form_for @folder do |f|
  - if @folder.errors.any?
    #error_explanation
      %h2= "#{pluralize(@folder.errors.count, "error")} prohibited this folder from being saved:"
      %ul
        - @folder.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
    = f.hidden_field :parent_id

  .actions
    - if @folder.new_record?
      = f.submit "Create Folder"
    - else
      = f.submit "Rename Folder"

app/views/folders/edit.html.haml
%h1 Editing folder

= render 'form'

- if @folder.parent
  = link_to "Back to '#{@folder.parent.name}' Folder", browse_path(@folder.parent)
- else
  = link_to "Back", root_url

app/views/folders/index.html.haml
%h1 Listing folders

%table
  %tr
    %th Name
    %th Parent
    %th User
    %th
    %th
    %th

  - @folders.each do |folder|
    %tr
      %td= folder.name
      %td= folder.parent_id
      %td= folder.user_id
      %td= link_to 'Show', folder
      %td= link_to 'Edit', edit_folder_path(folder)
      %td= link_to 'Destroy', folder, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Folder', new_folder_path

app/views/folders/new.html.haml
%h1 New folder
.breadcrumbs
  - if @current_folder #checking if we are under any folder
    = link_to "ShareBox", root_url
    - @current_folder.ancestors.reverse.each do |folder|
      » #{link_to folder.name, browse_path(folder)}
    »  #{@current_folder.name}
  - else #if we are not under any folder
    ShareBox

= render 'form'

- if @folder.parent
  = link_to "Back to '#{@folder.parent.name}' Folder", browse_path(@folder.parent)
- else
  = link_to "Back to Home page", root_url

app/views/folders/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @folder.name
%p
  %b Parent:
  = @folder.parent_id
%p
  %b User:
  = @folder.user_id

= link_to 'Edit', edit_folder_path(@folder)
\|
= link_to 'Back', folders_path