config/routes.rb
Filesucker::Application.routes.draw do
  resources :folders

  resources :assets
  match "assets/get/:id" => "assets#get", :as => "download" ,via: [:get]

  match "browse/:folder_id" => "home#browse", :as => "browse" , via: [:get]

  match "browse/:folder_id/new_folder" => "folders#new", :as => "new_sub_folder" , via: [:get]
  match "browse/:folder_id/new_file" => "assets#new", :as => "new_sub_file", via:[:get]

  match "browse/:folder_id/rename" => "folders#edit", :as => "rename_folder" , via:[:get]

  # for sharing folders
  match "home/share" => "home#share" , via:[:post]

  devise_for :users
  get "home/index"
  root :to => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
    #"We wish to display only the root folders which have no parents,
    # and only the files which are not under any folders.
    #@folders = current_user.folders.order("name desc")
    #@assets = current_user.assets.all
    debugger
    @being_shared_folders = current_user.shared_folders_by_others

    @folders = current_user.folders.roots
    @assets = current_user.assets.where("folder_id is NULL")

  end

  def browse
    #first find the current folder within own folders
    @current_folder = current_user.folders.find_by_id(params[:folder_id])
    @is_this_folder_being_shared = false if @current_folder #just an instance variable to help hiding buttons on View

    #if not found in own folders, find it in being_shared_folders
    if @current_folder.nil?
      folder = Folder.find_by_id(params[:folder_id])

      @current_folder ||= folder if current_user.has_share_access?(folder)
      @is_this_folder_being_shared = true if @current_folder #just an instance variable to help hiding buttons on View

    end

    if @current_folder
      #if under a sub folder, we shouldn't see shared folders
      @being_shared_folders = []

      #show folders under this current folder
      @folders = @current_folder.children

      #show only files under this current folder
      @assets = @current_folder.assets

      render :action => "index"
    else
      flash[:error] = "Don't be cheeky! Mind your own assets!"
      redirect_to root_url
    end
  end

  def destroy
    @asset = current_user.assets.find(params[:id])
    @parent_folder = @asset.folder #grabbing the parent folder before deleting the record
    @asset.destroy
    flash[:notice] = "Successfully deleted the file."

    #redirect to a relevant path depending on the parent folder
    if @parent_folder
      redirect_to browse_path(@parent_folder)
    else
      redirect_to root_url
    end
  end

  def share
    #first, we need to separate the emails with the comma
    email_addresses = params[:email_addresses].split(",")

    email_addresses.each do |email_address|
      #save the details in the ShareFolder table
      @shared_folder = current_user.shared_folders.new
      @shared_folder.folder_id = params[:folder_id]
      @shared_folder.shared_email = email_address

      #getting the shared user id right the owner the email has already signed up with ShareBox
      #if not, the field "shared_user_id" will be left nil for now.
      shared_user = User.find_by_email(email_address)
      @shared_folder.shared_user_id = shared_user.id if shared_user

      @shared_folder.message = params[:message]
      @shared_folder.save

      #now we need to send email to the Shared User
      UserMailer.invitation_to_share(@shared_folder).deliver
    end

    #since this action is mainly for ajax (javascript request), we'll respond with js file back (refer to share.js.erb)
    respond_to do |format|
      format.js {
      }
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
#container
  - unless user_signed_in?
    %h1 Welcome to File Sucker
    %p File sharing web application you can't ignore.
  - else
    #upload_link
      - unless @is_this_folder_being_shared
        %ul#top_menu
          - if @current_folder
            %li= link_to "Upload", new_file_path(@current_folder)
            %li= link_to "New Folder", new_sub_folder_path(@current_folder)
          - else
            %li= link_to "Upload", new_asset_path
            %li= link_to "New Folder", new_folder_path
      - else
        %h3
          This folder is being shared to you by #{@current_folder.user.email}


    .breadcrumbs
      - if @current_folder #checking if we are under any folder
        = link_to "ShareBox", root_url
        - @current_folder.ancestors.reverse.each do |folder|
          » #{link_to folder.name, browse_path(folder)}
        »  #{@current_folder.name}
      - else #if we are not under any folder
        ShareBox

    .asset_list_header
      .file_name_header File Name
      .file_size_header Size
      .file_last_updated_header Modified
    .asset_list
      - @being_shared_folders.each do |folder|
        -##todo implement  folder.shared?  method later on
        %div{class: "asset_details #{'shared_folder'}", id: "folder_#{folder.id}"}
          .file_name= link_to folder.name, browse_path(folder)
          .file_size -
          .file_last_updated -
          .actions

      - @folders.each do |folder|
        .asset_details.folder
          .file_name= link_to folder.name, browse_path(folder)
          .file_size -
          .file_last_updated -
          .actions
            .share
              = link_to "Share", "#", :folder_id => folder.id, :folder_name => folder.name unless @is_this_folder_being_shared
            .rename
              = link_to "Rename", rename_folder_path(folder) unless @is_this_folder_being_shared
            .delete
              = link_to "Delete", folder, :confirm => 'Are you sure?', :method => :delete unless @is_this_folder_being_shared
      - @assets.each do |asset|
        .asset_details
          .file_name= link_to  asset.uploaded_file.file.filename, download_url(asset)
          .file_size= asset.file_size
          .file_last_updated= nil
          .actions
            .download
              = link_to "Download", download_url(asset)
            .delete
              = link_to "Delete", asset, :confirm => 'Are you sure?', :method => :delete

    #invitation_form{style: "display:none", title: "Invite others to share"}
      = form_tag '/home/share' do
        %label{for: "email_addresses"} Enter recipient email addresses here
        %br/
        = text_field_tag 'email_addresses', "", :class => 'text ui-widget-content ui-corner-all'
        %br/
        %br/
        %label{for: "message"} Optional message
        %br/
        = text_area_tag 'message',"",  :class => 'text ui-widget-content ui-corner-all'
        = hidden_field_tag "folder_id"

app/views/home/share.js.erb
//closing the dialog box
$("#invitation_form").dialog("close");

//making sure we don't display the flash notice more than once
$("#flash_notice").remove();

//showing a flash message
$("#container").prepend("<div id='flash_notice'>Successfully shared the folder</div>");