config/routes.rb
Filesucker::Application.routes.draw do
  resources :folders

  resources :assets
  match "assets/get/:id" => "assets#get", :as => "download" ,via: [:get]

  match "browse/:folder_id" => "home#browse", :as => "browse" , via: [:get]

  match "browse/:folder_id/new_folder" => "folders#new", :as => "new_sub_folder" , via: [:get]
  match "browse/:folder_id/new_file" => "assets#new", :as => "new_sub_file", via:[:get]

  match "browse/:folder_id/rename" => "folders#edit", :as => "rename_folder" , via:[:get]

  # for sharing folders
  match "home/share" => "home#share" , via:[:post]

  devise_for :users
  get "home/index"
  root :to => "home#index"

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :user
  belongs_to :folder

  mount_uploader :uploaded_file, UploadedFileUploader
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_action :set_asset, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!  #authenticate for users before any methods is called

  def index
    @assets = current_user.assets
  end

  def show
  end

  def new
    @asset = current_user.assets.build
    if params[:folder_id] #if we want to upload a file inside another folder
      @current_folder = current_user.folders.find(params[:folder_id])
      @asset.folder_id = @current_folder.id
    end
  end

  def create
    @asset = current_user.assets.build(asset_params)
    if @asset.save
      flash[:notice] = "Successfully uploaded the file."

      if @asset.folder #checking if we have a parent folder for this file
        redirect_to browse_path(@asset.folder)  #then we redirect to the parent folder
      else
        redirect_to root_url
      end
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @asset.update(asset_params)
        format.html { redirect_to @asset, notice: 'Asset was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @asset.destroy
    respond_to do |format|
      format.html { redirect_to assets_url }
      format.json { head :no_content }
    end
  end

  def get
    asset = current_user.assets.find_by_id(params[:id])
    asset ||= Asset.find(params[:id]) if current_user.has_share_access?(Asset.find_by_id(params[:id]).folder)

    if asset
      send_file asset.uploaded_file.path, :type => asset.content_type
    else
      flash[:notice] = "Don't be cheeky! Mind your own assets!"
      redirect_to assets_path
    end
  end

  private
    def set_asset
      @asset = current_user.assets.find(params[:id])
    end

    def asset_params
      params.require(:asset).permit(:uploaded_file,:folder_id)
    end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_form.html.haml
= form_for @asset, :html => {:multipart => true} do |f|
  - if @asset.errors.any?
    #error_explanation
      %h2= "#{pluralize(@asset.errors.count, "error")} prohibited this asset from being saved:"
      %ul
        - @asset.errors.full_messages.each do |msg|
          %li= msg
  = f.label :uploaded_file, "File"
  = f.file_field :uploaded_file ,:class => 'file-btn'
  = f.hidden_field :folder_id
  .actions
    = f.submit 'Upload File'

:javascript
  var displayFile;

  displayFile = function(object) {
    var file, filename;
    file = object.value.split("\\");
    filename = file[file.length - 1];
    return $("#file-name").text(filename);
  };

  $("#file-btn").on("click", function() {
    return $("#file-picker").click();
  });

  $("#file-picker").on("change", function() {
    return displayFile(this);
  });

app/views/assets/edit.html.haml
%h1 Editing asset

= render 'form'

= link_to 'Show', @asset
\|
= link_to 'Back', assets_path

app/views/assets/index.html.haml
%h1 Listing assets

%table
  %tr
    %th  file name
    %th  file size
    %th  file_last_updated

  - @assets.each do |asset|
    %tr
      %td= link_to asset.uploaded_file.file.filename, download_url(asset)
      %td= asset.file_size
      %td= link_to 'Edit', edit_asset_path(asset)
      %td= link_to 'Destroy', asset, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Asset', new_asset_path

app/views/assets/new.html.haml
%h1 New asset
.breadcrumbs
  - if @current_folder #checking if we are under any folder
    = link_to "ShareBox", root_url
    - @current_folder.ancestors.reverse.each do |folder|
      » #{link_to folder.name, browse_path(folder)}
    »  #{@current_folder.name}
  - else #if we are not under any folder
    ShareBox
= render 'form'

- if @asset.folder
  = link_to "Back to '#{@asset.folder.name}' Folder", browse_path(@asset.folder)
- else
  = link_to "Back", root_url

app/views/assets/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_asset_path(@asset)
\|
= link_to 'Back', assets_path